### ISSUE TITLE
Specifying a plugin in .env appears not to work.

### ISSUE THREAD

**Issue by RAMilewski** [mozilla/corsica#54]
After installing corsica-image and specifying it in .env file it fails to load on **npm start**.

Adding corsica-image in the plugins section of config.js _**does**_ load the plugin on **npm start**

[env.txt](https://github.com/mozilla/corsica/files/1636781/env.txt)   (The original name was .env, but GitHub won't allow pasting hidden files).

**Comment by RAMilewski** [comment]
OK.  The keyword appears to be case sensitive.  Changing it to lower-case changes the behavior. 
It causes npm start to fail completely!

npm start
> corsica@2.0.0 start /home/ram/corsica
> node index.js
/home/ram/corsica/lib/core.js:86
  this.config.plugins.forEach(function(name, i) {
                      ^
TypeError: this.config.plugins.forEach is not a function
    at Corsica.loadPlugins (/home/ram/corsica/lib/core.js:86:23)
    at new Corsica (/home/ram/corsica/lib/core.js:28:8)
    at Object.start (/home/ram/corsica/lib/core.js:108:16)
    at Object.<anonymous> (/home/ram/corsica/index.js:2:6)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)

**Comment by RAMilewski** [comment]
Syntax of the plugins specification in .env was not correctly documented.  An example of the correct syntax is:

plugins=plugins=["brain","settings","proxy","census","command","content","glob","namer","tags","timer","corsica-image"]
